unbind r
bind r source-file ~/.tmux.conf

# change base command
set -g prefix C-s

set -g mouse on

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind -n C-M-h previous-window
bind -n C-M-l next-window
bind l new-window -c "#{pane_current_path}" 'lazygit'

# Fast scroll up (Ctrl+Shift+Up)
bind -n C-S-Up copy-mode \; send-keys -X page-up

# Fast scroll down (Ctrl+Shift+Down)
bind -n C-S-Down copy-mode \; send-keys -X page-down


set-option -g status-position top

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux#v2.1.3'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'

# Configure the catppuccin plugin
set -g @catppuccin_window_status_style "rounded"
set -g window-status-separator " "

set -g @catppuccin_window_default_text " #W"
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status "icon"
set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_number_position "left"

set -g @catppuccin_window_current_text " #W"
set -g @catppuccin_window_current_fill "all"


# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_directory}"
set -ag status-right "#{E:@catppuccin_status_session}"

# Update window name otomatis berdasarkan current path pane aktif
set -g allow-rename off


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run ~/.tmux/plugins/tmux/catppuccin.tmux
run '~/.tmux/plugins/tpm/tpm'
